server:
  port: ${PORT:8765}
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

spring:
  cloud:
    kubernetes:
      ribbon:
        enabled: true
        
info:
  component: Zuul Server
  
endpoints:
  actuator:
    path: /mngmt/actuator
  env:
    path: /mngmt/env
  health:
    path: /mngmt/health
  info:
    path: /mngmt/info

dynamiczuul:
# we can disable the kubernetes service discovery and use Eureka
  useEurekaServices: false
# For local development
  localServices: false
# Default services port( by now all services should be in the same port)
  servicesPort: ${SERVICES_PORT:9000}
# Prefix for the url, for example: http://localhost:8765/services/openshift-sb-ms-store
  servicesPrefix: services
# If we want the url's to remove a prefix, for example for using http://localhost:8765/services/ms-store
  removeAppPrefix: false   
  appPrefix: openshift-sb-
# Custom routes, if we want to use a different name for a service, for example to use a blue green deployment
# can be specified here
  customRoutes:
    lg-ms-customersblue:
        serviceId: lg-ms-customers

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
